import './About.css';

export const About = () => {
    return (
        <div className="about-container row text-center">
            <h1>About</h1>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed placerat ultrices tempor. Vivamus posuere dignissim tortor quis tristique. Aenean accumsan scelerisque ante. Etiam eros ex, sollicitudin ac mauris eget, scelerisque dignissim magna. Nullam ornare porta mauris eu dignissim. In et dolor justo. Vestibulum leo erat, dignissim a ligula sit amet, laoreet accumsan nisl. Etiam sagittis justo ipsum, eu imperdiet sapien tristique ac. Nulla sodales pellentesque dui, vitae molestie tellus egestas pharetra. Nunc scelerisque euismod nisi, ut bibendum nibh sagittis eget. Donec nisi mauris, fermentum ut ex nec, scelerisque fermentum ligula. Donec blandit vehicula lacus commodo convallis. Mauris congue dolor et. Sed sed metus vitae ante lacinia laoreet. Etiam nisi augue, lobortis eu ultricies a, interdum in nunc. Suspendisse pulvinar metus vel leo euismod, sit amet feugiat elit varius. Nulla rutrum mi augue, eget gravida diam efficitur at. Vivamus imperdiet ac lorem ac dignissim. Aliquam rutrum elit quis velit posuere, nec tristique sapien pretium. Sed cursus ultricies augue, consectetur consectetur orci porttitor ut.Praesent porttitor sagittis molestie. Nullam id turpis eget ligula ultrices ullamcorper a in quam. Phasellus tempor ex malesuada, tristique lacus feugiat, porta augue. Proin pretium mi venenatis, dapibus risus a, ullamcorper est. Phasellus vestibulum, risus vel volutpat pharetra. Donec fermentum, leo et iaculis fermentum, tellus quam elementum odio, nec consequat mauris ex accumsan odio. Curabitur ullamcorper tincidunt enim, a dictum est accumsan vel. Phasellus sodales accumsan arcu et placerat.</p>
            <h2>What we do</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ante nisl, congue et nibh sed, volutpat feugiat est. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed lacinia enim non augue feugiat pellentesque. Duis erat lorem, eleifend a tortor faucibus, feugiat pulvinar sapien. Proin congue ullamcorper risus non lobortis. Vestibulum arcu metus, bibendum eu hendrerit id, malesuada sit amet nunc. Etiam dapibus aliquet viverra. Cras fringilla volutpat justo, non venenatis lectus malesuada sed. Ut feugiat iaculis ligula consectetur cursus. Nam mattis ipsum et turpis posuere, quis vulputate justo placerat. Vestibulum id elit in justo egestas pulvinar eu vitae. Donec dictum quam eu metus aliquet, nec vehicula urna rhoncus. Integer rutrum cursus augue ut vestibulum. Nunc in neque eget lacus accumsan euismod in id quam. Morbi vehicula porta odio, ac eleifend ante. Mauris sed gravida arcu, eu finibus enim. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; In vulputate, eros at gravida mattis, orci lorem faucibus purus, ac porttitor leo nisl eu diam. In eget aliquam quam, a sodales lectus. Mauris at mauris viverra, imperdiet diam auctor, finibus leo. Donec elementum, metus at cursus pulvinar, mauris quam laoreet urna, eget efficitur ante purus sit. Proin sollicitudin nisl vitae quam convallis pharetra. Etiam sit amet laoreet purus.</p>
        </div>
    );
}